### ISSUE TITLE
Babel polyfill not included: regeneratorRuntime missing

### ISSUE THREAD

**Issue by Risto-Stevcev** [bodil/eulalie#40]
Trying to import eulalie doesn't work because the babel regenerator polyfill isn't included in the module:

``` bash
npm install eulalie --save
node
```

``` js
> var e = require('eulalie')
ReferenceError: regeneratorRuntime is not defined
    at isGen (/home/velvet/git/javascript/parse-robots/node_modules/eulalie/index.js:71:7)
    at seq (/home/velvet/git/javascript/parse-robots/node_modules/eulalie/index.js:362:7)
    at sat (/home/velvet/git/javascript/parse-robots/node_modules/eulalie/index.js:584:10)
    at Object.<anonymous> (/home/velvet/git/javascript/parse-robots/node_modules/eulalie/index.js:750:22)
```

This [StackOverflow post](http://stackoverflow.com/questions/28976748/regeneratorruntime-is-not-defined) mentions a workaround where you include `require('babel-polyfill')` before importing the offending module.

**Comment by jgoux** [comment]
I have the same issue. I'd prefer not to include babel-polyfill as I'm on node.js v5.

**Comment by Risto-Stevcev** [comment]
@bodil @jgoux Actually I don't think that this can change because `regeneratorRuntime` is required for generators. You could avoid this if you use parsimmon for combinatorial parsing instead, but it won't have the generator sugar. You could use generator style sugar for parsimmon by using do notation (like my `do-notation` library) since the parsers are monads and implement the FL `chain` method, but you would still need `babel-polyfill` to support generator syntax for `do-notation`.

I'm considering closing this as I don't see a way around including `babel-polyfill`, though it would be nice to mention that it's required because the library uses generators.

**Comment by bodil** [comment]
Actually, I wonder if the best way around this is to just distribute this library as ES6, leaving any compilation steps to the consumer. It made sense to distribute the Babel output at the time because that's how I was consuming it, but I'm not so sure it was a good idea any more.

**Comment by Risto-Stevcev** [comment]
I don't know. I think that would make the library harder to use in the short run even if the dev is also using babel, since the `node_modules/eulalie` path would need to be compiled along with the project they're working on. Though Node already supports generators and is going to support ES6 module syntax soon enough, and then you could just use it as is without babel.

**Comment by bodil** [comment]
lmao if you think I've restricted myself to ES6 syntax in this codebase. :)

I think the only big issue is Regenerator (and the Babel polyfills in general) and how to deal with it. I'm going to try and build a new package compiled with Node 4 as a target, which, I think, should eliminate the need for the polyfills in exchange for certain platform requirements.
