### ISSUE TITLE
Parser returned unexpected value: GeneratorFunctionPrototype

### ISSUE THREAD

**Issue by ccorcos** [bodil/eulalie#59]
I'm trying to figure out whats going on here:

```
  Error: Parser returned unexpected value: GeneratorFunctionPrototype { _invoke: [Function: invoke] }
    badValue (node_modules/eulalie/index.js:286:10)
    input (node_modules/eulalie/index.js:342:11)
    Object.parse (node_modules/eulalie/index.js:262:10)
    Test.fn (lib/index.test.js:165:18)
```

I'm just running the example from the README:

```js
import test from 'ava';
import * as p from "eulalie";

// Combine a sequence of parsers into a bigger parser using a generator
const parser = p.seq(function*() {
  // Parse a sequence of 1 or more upper case letters
  const {value: method} = yield p.many1(p.upper);
  // Consume 1 or more spaces
  yield p.spaces1;
  // Parse a sequence of 1 or more non-whitespace characters
  const {value: path} = yield p.notSpaces1;
  // Consume 1 or more spaces
  yield p.spaces1;
  // Match the string "HTTP/"
  yield p.string("HTTP/");
  // Parse a new sequence
  const {value: version} = yield p.seq(function*() {
    // Parse 1 or more digits
    const {value: left} = yield p.many1(p.digit);
    // Match a period
    yield p.char(".");
    // Parse 1 or more digits
    const {value: right} = yield p.many1(p.digit);
    // Assemble the parsed values
    return `${left}.${right}`;
  });
  // Return the final parsed value
  return {method, path, version};
});


test('here', t => {
  const result = p.parse(parser, p.stream("GET /lol.gif HTTP/1.0"));
  t.deepEqual(result.value, {
    method: "GET",
    path: "/lol.gif",
    version: "1.0"
  })
})
```

I'm using babel stage-0 as well...

**Comment by ccorcos** [comment]
hmm. it works when I run `node --harmony` and use the repl... maybe I'm messing something up with ava or something...

**Comment by bodil** [comment]
Yes, that's some sort of transpilation error, I'm pretty sure. Might be Ava isn't loading the transpiler's runtime support (babel-runtime or whatever)?

**Comment by ccorcos** [comment]
Yeah, I'll look closer on Sunday, but I think it might have to do with the
isGen function. Following the stack trace, it thinks it's just a
function... And that makes sense given it's transpired to ES5

**Comment by ccorcos** [comment]
Never really ended up figuring this out -- I was transpiling with babel and then running ava, and thats when I got the error. If I just run ava, everythign works so I'm just going to stick with that for now. 

Really cool library btw @bodil :) Any thoughts about TCO?

**Comment by bodil** [comment]
Fully prepared to accept it's my `isGen` function at fault - transpiling is messy. ☺️

I should probably revisit this as pure ES6 - generators are pretty universally supported now.
