### ISSUE TITLE
How would `notString` work?

### ISSUE THREAD

**Issue by ccorcos** [bodil/eulalie#60]
I'm trying to make a markdown parser and I'm working on inline tokens for italic and bold using `*` and `**` to wrap a string. The thing is, you should be able to have italics inside bold and vice versa.

Basically, if `*` or `**` are the tokens we're interested in, we want to make sure that there's a space before the start token and a space after the end token and we want the inside string the return value.

Here's what I have prototyped so far:

```js
const italic = seq(function*() {
  yield char('*')
  const firstChar = yield both([
    notChar(' '),
    notChar('*'),
  ])
  const {value: s} = yield many1(either([
    seq(function* () {
      yield char('\\')
      yield item
    }),
    notString('* ')
  ]))
  yield char('*')
  return s
})
```

I tried creating `notString` from the `string` function but I think that's the wrong approach because I'm not sure I want `notString` to consume anything. 

```js
function notString(s) {
  return seq(function*() {
    let i = 0
    while(i < s.length) {
      yield notChar(s[i])
    }
  })
}
```

So maybe I could write something like `notString('* ', item)` which means it will only consume on character at a time while checking ahead.

```js
function notString(s, after) {
  return function(input) {
    return input.startsWith(s) ? parse(input, after) : error(input)
  }
}
```

I'm pretty sure I can get something to work here, but I'm curious if you have any recommendations about the cleanest way to do this. One thing I haven't actually accounted for is nesting parsers, but I think that would be easier as a second pass over the result rather than composing each other...

**Comment by bodil** [comment]
Not 100% sure I understand what you want `notString` to do, but it seems like simple lookahead without consuming input? In that case, just store the point in the stream at which you start the lookahead, and return that as the `next` property of the `ParseResult` when you're done. You're not really consuming the stream, after all, just moving the index pointer around.

Something like (warning, 100% untested code):

```js
function lookahead(p) {
  return function(input) {
    const start = input;
    const r = parse(p, input);
    return isResult(r) ? result(r.value, start, start, "") : r;
  };
}
```

So you'd just wrap your notString parser in that, and it'll still return a parse result or failure, but it'll be back where it was before your parser started. That's the idea anyway, don't trust my pseudocode. ☺️
